# Yan Pan, April 2023. Allow pods to start 0-replica service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-int-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "events", "pods/log"]
  verbs: ["get", "list", "watch", "logs"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-int-role-binding
roleRef:
  kind: Role
  name: app-int-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: internal-service-account
