# YYYan
# all docker service use docker repo, and must be built in advance
# restart always to allow delayed startup procedures

version: "staging"

services:

  ingress: # port=env
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - fast-mongo
      - mlops-int
    volumes:
      - ./nginx/conf.template:/etc/nginx/templates/yyy.conf.template
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=9001
      - HOSTNAME=v2.yan.fi
      - MONGOEXP_URL=http://fast-apps:8001
      - APP_URL=http://fast-mongo:8001
      - BOT_URL=http://y-bot-y:8002
      - OURA_URL=http://mlops-int:8101
  
  fast-apps:
    restart: always
    image:  yyyaaan/fastapps:latest
    pull_policy: always
    volumes:
      - ./tmpmntdata:/mnt/shared
    command: "uvicorn main:app --root-path /app --reload --host 0.0.0.0 --port 8001;"  
    env_file:
      - env.env

  y-bot-y:
    restart: always
    image:  yyyaaan/yboty:latest
    pull_policy: always
    volumes:
      - ./tmpmntdata:/mnt/shared
    command: "uvicorn main:app --root-path /bot --reload --host 0.0.0.0 --port 8002;"  
    env_file:
      - env.env

  mlops-int: # port=command
    restart: always
    image:  yyyaaan/mlopsint:latest
    volumes:
      - ./tmpmntdata:/mnt/shared
    command: "uvicorn app:app --root-path /app001 --host 0.0.0.0 --port 8101;"  

