# YYYan
# all docker service use docker repo, and must be built in advance
# restart always to allow delayed startup procedures

version: "staging"

services:

  ingress: # port=env
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - fast-mongo
      - fast-1
    volumes:
      - ./nginx/conf.template:/etc/nginx/templates/yyy.conf.template
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
      - "9001:9001"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=9001
      - HOSTNAME=v2.yan.fi
      - MONGOEXP_URL=http://fast-mongo:8001
      - APP_URL=http://fast-mongo:8001
      - APP001_URL=http://mlops-int:8101
      - APP002_URL=http://localhost:3838
      - APP003_URL=http://host.docker.internal:3838
  
  fast-mongo: # port=command
    restart: always
    image:  yyyaaan/fastapi001mongo
    pull_policy: always
    volumes:
      - ./tmpmntdata:/mnt/shared
    command: "uvicorn main:app --root-path /app --reload --host 0.0.0.0 --port 8001;"  
    env_file:
    - env.env

  mlops-int: # port=command
    restart: always
    image:  yyyaaan/mlopsint
    volumes:
      - ./tmpmntdata:/mnt/shared
    command: "uvicorn app:app --root-path /app001 --host 0.0.0.0 --port 8101;"  

