# YYYan
# logging needs to be started first

version: "efk-logging-stack"
services:

  fluentd:
    build: ./fluentd
    restart: always
    links:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:8.8.1
    restart: always
    volumes: 
      - ./tmpmntdata/efklogging/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: kibana:8.8.1
    restart: always
    links: # Links kibana service to the elasticsearch container
      - elasticsearch
    ports:
      - 5601:5601
    volumes: 
      - ./tmpmntdata/efklogging/kibana:/usr/share/kibana/data
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'



