# YYYan
# all docker service use docker repo, and must be built in advance
# restart always to allow delayed startup procedures

version: "local-dev-only"
services:

  ingress: # port=env
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - mongo-express
    volumes:
      - ./nginx/conf.template:/etc/nginx/templates/yyy.conf.template
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
      - "9001:9001"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=9001
      - HOSTNAME=localhost:9001
      - MONGOEXP_URL=http://mongo-express:8081
      - APP_URL=http://fast-apps:8001
      - VUE_URL=http://frontend:8997
      - BOT_URL=http://y-bot-y:8998
      - OURA_URL=http://y-oura-y:8999

  mongo: # port=27017
    restart: always
    image: mongo
    volumes:
      - ./tmpmntdata/mongo:/data/db 
    env_file:
      - env.env

  mongo-express: # port=8081
    restart: always
    image: mongo-express
    depends_on:
      - mongo
    env_file:
      - env.env
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_SITE_BASEURL=/mongoadmin

  # fast-mongo: # port=command
  #   build:
  #     context: ./fast-api-mongo-min
  #   volumes:
  #     - ./tmpmntdata:/mnt/shared
  #     - ./fast-api-mongo-min/src:/app
  #   command: "uvicorn main:app --root-path /app --reload --host 0.0.0.0 --port 8001;"  
  #   depends_on:
  #   - mongo
  #   env_file:
  #   - env.env

  # use built image, NOT support rebuilding
  fast-apps: 
    restart: always
    image: yyyaaan/fastapps:latest
    volumes:
      - ./tmpmntdata:/mnt/shared
      - ./fast-api-mongo-min/src:/app
      - ../yBotY/src:/app/appbot
      - ../yBotY/src/templates/bot:/app/templates/bot
    command: "uvicorn main:app --root-path /app --reload --host 0.0.0.0 --port 8001;"  
    depends_on:
    - mongo
    env_file:
    - env.env

  y-oura-y:
    restart: always
    build:
      context: ../yOuraY
    volumes:
      - ./tmpmntdata:/mnt/shared
      - ../yOuraY/src:/app
    command: "uvicorn main:app --root-path /oura --reload --host 0.0.0.0 --port 8999;"  
    depends_on:
    - mongo
    env_file:
    - env.env

  y-bot-y:
    restart: always
    build:
      context: ../yBotY
    volumes:
      - ./tmpmntdata:/mnt/shared
      - ../yBotY/src:/app
    command: "uvicorn main:app --root-path /bot --reload --host 0.0.0.0 --port 8998;"  
    depends_on:
    - mongo
    env_file:
    - env.env

  frontend:
    restart: always
    build:
      context: ./frontend
    volumes:
      - ./tmpmntdata:/mnt/shared
    environment:
      - VUE_PATH=/vue/
    command: [ "http-server", "dist", "-p", "8997" ]

  # for analyzing dependencies
  dev-py311-tools:
    build:
      context: .
      dockerfile: ./tmpmntdata/dev/dockerfile311
    volumes:
      - ./tmpmntdata/dev/:/mnt/
    command: |
      bash -c "
      pip-compile requirements.in
      tail -f /dev/null
      "
