# YYYan
# logging needs to be started first

version: "efk-logging-stack"
services:

  fluentd:
    build: ./fluentd
    restart: always
    links:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./tmpmntdata/fluentd/:/var/log/fluent/

  elasticsearch:
    image: elasticsearch:8.8.1
    restart: always
    volumes: 
      - ./tmpmntdata/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    # index creation: http://localhost:5601/app/management/kibana/dataViews
    image: kibana:8.8.1
    restart: always
    links:
      - elasticsearch
    ports:
      - 5601:5601
    volumes: 
      - ./tmpmntdata/kibana:/usr/share/kibana/data
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
