# YYYan
# all docker service use docker repo, and must be built in advance
# restart always to allow delayed startup procedures

version: "production"

services:

  ingress: # port=env
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - fastapi-backend
      - vue-frontend
    volumes:
      - ./nginx/conf.template.prod:/etc/nginx/templates/yyy.conf.template
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
      - "9001:9001"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=9001
      - HOSTNAME=v2.yan.fi
      - VUE_URL=http://vue-frontend:80
      - API_URL=http://fastapi-backend:8001
      - KIBANA_URL=http://host.docker.internal:5601 # not in use
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: yyy.nginx

  vue-frontend:
    restart: always
    pull_policy: always
    image: yyyaaan/yanfivuejs:latest
    command: ["nginx", "-g", "daemon off;"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: yyy.vuejs
  
  fastapi-backend:
    restart: always
    pull_policy: always
    image: yyyaaan/fastapps:latest
    volumes:
      - ./tmpmntdata:/mnt/shared
    extra_hosts:
      - "host.docker.internal:host-gateway" # for elastic search
    env_file:
      - env.env
    environment:
      - FAST001_HOSTNAME_ROOTPATH=v2.yan.fi/api
    command: "uvicorn main:app --root-path /api --host 0.0.0.0 --port 8001;"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: yyy.fastapi


