# YYYan
# all docker service use docker repo, and must be built in advance
version: "local-dev-only"

services:

  ingress: 
    image: nginx
    depends_on:
      - fast-1
      - mlflow
    volumes:
      # - ./ingress/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ingress/index.html:/usr/share/nginx/html/index.html
      - ./ingress/nginx.conf.template:/etc/nginx/templates/yyy.conf.template
    ports:
      - "8001:8001"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8001
      - APP001_URL=http://fast-1:8101
      - APP002_URL=http://mlflow:9201
      - APP003_URL=http://fast-1:8101
  
  fast-1:
    image:  yyyaaan/mlopsint
    volumes:
      - ./tmpmntdata:/mnt/shared
    command: "uvicorn app:app --root-path /app001 --host 0.0.0.0 --port 8101;"  
    ports: 
      - "8101:8101"

  mlflow:
    image:  yyyaaan/mlflowserver
    volumes:
      - ./tmpmntdata:/mnt/shared
    command: "sh start_mlflow.sh"  
    ports: 
      - "9201:9201"

