# YYYan
# all docker service use docker repo, and must be built in advance
# restart always to allow delayed startup procedures

version: "production"

networks:  # docker-compose-stack.yaml
  default:
    name: backbone
    external: true

services:
  ingress: # port=env
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - fastapi-backend
      - vue-frontend
    volumes:
      - ./nginx/conf.template.prod:/etc/nginx/templates/yyy.conf.template
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - /etc/apache2/.htpasswd:/etc/apache2/.htpasswd
    ports:
      - "9001:9001"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=9001
      - HOSTNAME=v2.yan.fi
      - VUE_URL=http://vue-frontend:80
      - API_URL=http://fastapi-backend:8001
      - PDF_URL=http://stirling-pdf:8080
      - KIBANA_URL=http://kibana:5601
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: yyy.nginx

  vue-frontend:
    restart: always
    pull_policy: always
    image: yyyaaan/yanfivuejs:latest
    command: ["nginx", "-g", "daemon off;"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: yyy.vuejs
  
  fastapi-backend:
    restart: always
    pull_policy: always
    image: yyyaaan/fastapps:latest
    volumes:
      - ./tmpmntdata:/mnt/shared
    env_file:
      - env.env
    environment:
      - FAST001_HOSTNAME_ROOTPATH=v2.yan.fi/api
    command: "uvicorn main:app --root-path /api --host 0.0.0.0 --port 8001;"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: yyy.fastapi

  kibana:
    image: kibana:8.8.1
    restart: always
    ports:
      - 5601:5601
    volumes: 
      - ./tmpmntdata/kibana:/usr/share/kibana/data
    environment: 
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      SERVER_HOST: "0.0.0.0"
      SERVER_BASEPATH: "/kibana"
      SERVER_REWRITEBASEPATH: true


  stirling-pdf:
    image: frooodle/s-pdf:latest
    volumes:
      - ./tmpmntdata/pdf/trainingData:/usr/share/tesseract-ocr/5/tessdata
      - ./tmpmntdata/pdf/extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - APP_ROOT_PATH='/pdf'