# Yan Pan
# this is special action that only runs on specified branch
name: MultiApp-Staging
on:
  push:
    branches:
    - new-vector-db

jobs:

  docker-image-build-push:
    runs-on: ubuntu-latest
    environment: 	DockerHubConnected
    
    steps: 
    - name: Checkout Parent Repo
      uses: actions/checkout@v3

    - name: Checkout yBotY Repo
      uses: actions/checkout@v3
      with:
        path: ./yBotY
        repository: yyyaaan/yBotY

    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_KEY }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: dockerfileMultiApps
        push: true
        tags: "yyyaaan/fastapps:staging"
