# Yan Pan
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and Build Fast API Mongo Min App

on: [push]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

permissions:
  contents: read

env:
  FAST001_MONGO_URL: "mongodb://na:not-needed-for-test@mongo/na"
  FAST001_MONGO_DB_NAME: "db"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install mock db and pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mongomock_motor
        pip install -r ./fast-api-mongo-min/requirements.txt
    
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./fast-api-mongo-min/src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./fast-api-mongo-min/src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Unit test
      run: |
        cd ./fast-api-mongo-min/src/
        python -m pytest --doctest-modules --junitxml=test-results.xml

    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./fast-api-mongo-min/src/test-results.xml
      if: ${{ always() }}
