# Yan Pan
name: FastAPI-Multi-Apps
on:
  push:
    branches:
    - main

jobs:

  docker-image-build-push:
    runs-on: ubuntu-latest
    environment: 	DockerHubConnected
    
    steps: 
    - name: Checkout Parent Repo
      uses: actions/checkout@v3

    - name: Checkout yBotY Repo
      uses: actions/checkout@v3
      with:
        path: ./yBotY
        repository: yyyaaan/yBotY

    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_KEY }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: dockerfileMultiApps
        push: true
        tags: "yyyaaan/fastapps"

  CSC-VM-deployment:
    runs-on: ubuntu-latest
    environment: 	DockerHubConnected
    needs:
    - docker-image-build-push

    steps:
    - name: SSH Commands
      run: |
        echo "${{ secrets.CSC_KEY }}" | tr -d '\r' > key.pem
        chmod 400 key.pem
        ssh -i key.pem yan@${{ secrets.CSC_IP }} -o "StrictHostKeyChecking no" << 'END'
        cd yyy-cluster
        docker compose -f docker-compose-prod.yaml down
        git pull
        docker compose -f docker-compose-prod.yaml pull
        docker compose -f docker-compose-prod.yaml up > tmp.$(date +"%Y%m%d").log 2>&1 &
        END
