# Yan Pan
name: FastAPI-Multi-Apps
on:
  push:
    branches:
    - main

jobs:

  Push_Docker_Image:
    runs-on: ubuntu-latest
    environment: 	DockerHubConnected
    
    steps: 
    - name: Checkout Parent Repo
      uses: actions/checkout@v3

    - name: Checkout yBotY Repo
      uses: actions/checkout@v3
      with:
        path: ./yBotY
        repository: yyyaaan/yBotY

    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_KEY }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: dockerfileMultiApps
        push: true
        tags: "yyyaaan/fastapps"

